#!/bin/bash
export PATH="/Users/antonioreid/.nvm/versions/node/v20.9.0/bin:$PATH"

if [ -d nestjs_api ]; then
  cd nestjs_api && pnpm lint-staged
else
  echo "Directory 'nestjs_api' not found"
  exit 1
fi
